# Generated by Django 3.2.8 on 2021-12-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(help_text='Introduce la observacion', max_length=500)),
                ('direccionip', models.CharField(help_text='Introduce la direccion IP', max_length=15)),
                ('equipo', models.CharField(help_text='Introduce el nombre del equipo', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='registros',
        ),
    ]
